### PR TITLE
Update using-gulp.md

### PR DESCRIPTION
**Pull request by aldonetti**

### CODE REVIEW

**Comment by gosali** [comment]
Hi @aldonetti , we are still in discussing, will update the decision later soon. 
  
Thanks for your support,
Microsoft C&E Localization Team

**Comment by v-maudel** [comment]
Hello, @aldonetti , 

Thank for your contribution. We are currently reviewing it. We will communicate the decision taken  accordingly. 
 
Thanks for your time and support on this.

Kind regards,

Microsoft C&E Localization Team

**Comment by carolinacmoravia** [comment]
Hello, @aldonetti, 

Thank you for your feedback and suggestion! 

The feedback is considered. Yet, this PR contains merge conflict, please resolve at your end, or close it then submit another new one.  It may happen after we update the content on http://azure.microsoft.com.
		
Microsoft C&E Localization Team

**Comment by gosali** [comment]
@aldonetti : Thank you for your feedback and suggestion! 
  
The feedback is considered. We will tune part of  your feedbacks in order to comply with Microsoft Style Guide, then release this article in the next loc release round.
  
Microsoft C&E Localization Team

**Pull request merged**
