### PR TITLE
Fix french grammar

### PR DESCRIPTION
**Pull request by miiitch**

### CODE REVIEW

**Comment by v-tisip** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo because branch live has been deleted.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C15%5C5b5144b9-01d0-4c26-c245-8939f1d0e105%5CPullRequest%5C201711152129005084-6%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=jHdWPxTOVXUJC2qa%2FpxVAnR08i%2B9zaJpSqugpJ3%2Biyk%3D&st=2017-11-15T21%3A24%3A05Z&se=2017-12-16T21%3A29%3A05Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by gosali** [comment]
Hi @miiitch , we are still in discussing, will update the decision later soon. 
  
Thanks for your support,
Microsoft C&E Localization Team

**Comment by v-radelg** [comment]
@miiitch , Thank you for your feedback and suggestion! 

The suggestion will be merged to the production, we will re-release this articles in the next loc release round.

Microsoft C&E Localization Team

**Comment by v-tisip** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo because branch live has been deleted.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C17%5C5b5144b9-01d0-4c26-c245-8939f1d0e105%5CPullRequest%5C201711171824240759-6%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=tON9zMWWpJVEL1GmBGYjDBXW5NDTog27Y%2BEVg4cO%2BVo%3D&st=2017-11-17T18%3A19%3A31Z&se=2017-12-18T18%3A24%3A31Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
