### PR TITLE
French Improvment for aspnetcore/migration/configuration.md

### PR DESCRIPTION
**Pull request by mikaelkrief**
French Improvment for aspnetcore/migration/configuration.md

### CODE REVIEW

**Comment by agriffard** [comment]
Salut. Merci d'utiliser 'ASP.NET Core MVC' et non 'ASP.NET MVC Core'.
ça peut paraître un détail mais ça a de l'importance et comme ça, le même terme sera utilisé partout.

Petite typo: 'inclu' => 'inclut'

**Comment by mikaelkrief** [comment]
Mise à jour effectuée

**Comment by v-maudel** [comment]
Hello, @mikaelkrief , 

Thank for your contribution. We are currently reviewing it. We will communicate the decision taken  accordingly. 
 
Thanks for your time and support on this.

Kind regards,

Microsoft C&E Localization Team

**Comment by v-maudel** [comment]
Hello, @mikaelkrief , 

Thank you for your feedback and suggestions.
 
This proposed file change has been accepted. The suggestion will be merged to this repository.  We will release this article on the next localization release round. 
 
Many thanks for your support.

Kind regards,

Microsoft C&E Localization Team

**Pull request merged**
